config/routes.rb
Myroutes::Application.routes.draw do
  
  resources :companies do
    resources :pharmacies
  end
  
  root :to => 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many  :pharmacies
end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_filter :get_company
  # GET /pharmacies
  # GET /pharmacies.json
  def index
    @pharmacies = @company.pharmacies.all
  end

  # GET /pharmacies/1
  # GET /pharmacies/1.json
  def show
    @pharmacy = @company.pharmacies.find(params[:id])
  end

  # GET /pharmacies/new
  # GET /pharmacies/new.json
  def new
    @pharmacy = @company.pharmacies.build
  end

  # GET /pharmacies/1/edit
  def edit
    @pharmacy = @company.pharmacies.find(params[:id])
  end

  # POST /pharmacies
  # POST /pharmacies.json
  def create
    @pharmacy = @company.pharmacies.build(params[:pharmacy])
    if @pharmacy.save
      redirect_to(company_pharmacies_url(@company), :notice => 'Pharmacy was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /pharmacies/1
  # PUT /pharmacies/1.json
  def update
    @pharmacy = @company.pharmacies.find(params[:id])
    if @pharmacy.update_attributes(params[:pharmacy])
      redirect_to(company_pharmacies_url(@company), :notice => 'Pharmacy was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /pharmacies/1
  # DELETE /pharmacies/1.json
  def destroy
    @pharmacy = @company.pharmacies.find(params[:id])
    @pharmacy.destroy
    redirect_to(company_pharmacies_url(@company))
  end
  
 protected
  
  def get_company
    @company = Company.find_by_id(params[:company_id])
    redirect_to root_path unless @company
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.number_field :version %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Version</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.version %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @company.name %>
</p>

<p>
  <b>Version:</b>
  <%= @company.version %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myroutes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pharmacies/_form.html.erb
<%= form_for([@company, @pharmacy]) do |f| %>
  <% if @pharmacy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pharmacy.errors.count, "error") %> prohibited this pharmacy from being saved:</h2>

      <ul>
      <% @pharmacy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pharmacies/edit.html.erb
<h1>Editing pharmacy</h1>

<%= render 'form' %>

<%= link_to 'Show', company_pharmacy_path(@pharmacy) %> |
<%= link_to 'Back', company_pharmacies_path(@company) %>

app/views/pharmacies/index.html.erb
<h1>Listing pharmacies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pharmacies.each do |pharmacy| %>
  <tr>
    <td><%= pharmacy.name %></td>
    <td><%= pharmacy.company_id %></td>
    <td><%= link_to 'Show', company_pharmacy_path(@company, pharmacy) %></td>
    <td><%= link_to 'Edit', edit_company_pharmacy_path(@company, pharmacy) %></td>
    <td><%= link_to 'Destroy', "/companies/#{params[:company_id]}/pharmacies/#{pharmacy.id}", confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pharmacy', new_company_pharmacy_path(@company) %>

app/views/pharmacies/new.html.erb
<h1>New pharmacy</h1>

<%= render 'form' %>

<%= link_to 'Back', company_pharmacies_path(@company) %>

app/views/pharmacies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pharmacy.name %>
</p>

<p>
  <b>Company:</b>
  <%= @pharmacy.company_id %>
</p>


<%= link_to 'Edit', edit_company_pharmacy_path(@company, @pharmacy) %> |
<%= link_to 'Back', company_pharmacies_path(@company) %>